version: '3'

services:
  mage2kishbox-nginx:
    build: "./nginx/"
    container_name: "nginx"
    depends_on:
      - mage2kishbox-php8.1
    volumes:
     # - /etc/nginx/certs:/etc/ssl/nginx
      - ../www:/var/www
      - ./nginx/sites:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.1

    
  mage2kishbox-php8.1:
    build: "./php/8.1/"
    container_name: php8.1
    environment:
      COMPOSER_HOME: "/tmp/composer"      
    volumes:
      - ../www:/var/www
    ports:
      - 9000
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.11

  mage2kishbox-mysql8:
    build: "./mysql/8.0/"
    container_name: "mysql8"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - ../data/mysql/8.0/data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.3

  mage2kishbox-mailhog:
    image: mailhog/mailhog
    container_name: "mailhog"
    user: root
    expose:
      - 80
    ports:
      - "1025:80"  
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.4
  mage2kishbox-sftp:
    image: atmoz/sftp
    container_name: "sftp"
    volumes:
      - ./sftp/host/upload:/home/lamp/test-sftp/upload
      # - /home/lamp/.ssh/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
    ports:
      - "2222:22"
    command: foo:pass:1001:2000:inbox,outbox
#    command: foo::1001
    networks:
      - docker-mage2kishbox-network
  mage2kishbox-rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: "rabbit"
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq1"
    restart: "no"
    networks:
      - docker-mage2kishbox-network

  mage2kishbox-varnish:
    build: "./varnish"
    container_name: varnish
    privileged: true
    ports:
      - "80:80"
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.5
    #extra_hosts:
      #- "hydro.loc:145.23.1.1"

  mage2kishbox-elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200"
      - "9300"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      docker-mage2kishbox-network:
        ipv4_address: 145.23.1.23

networks:
  docker-mage2kishbox-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 145.23.0.0/16

